#!/bin/bash
set -e

# Remover ícone no desktop (caso precise)
if [ -f "/usr/share/applications/magic.desktop" ]; then
    rm /usr/share/applications/magic.desktop
fi

# Limpar o cache de ícones (caso precise)
if [ -x "/usr/bin/update-desktop-database" ]; then
    update-desktop-database
fi

exit 0
